#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/Projects/Enviro/main &
$HOME/.config/polybar/launch.sh &
dunst &
picom &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap 20
bspc config border_width 2
bspc config normal_border_color "#313244"
bspc config focused_border_color "#7f849c"

bspc config focus_follows_pointer true

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
